import { Injectable} from '@angular/core';

const COUNTRY_DIAL_CODE: Object[] = [
  { dial: "93", code: "AF", name:"Afghanistan"},
{ dial: "358", code: "AX", name:"Aland Islands"},
{ dial: "355", code: "AL", name:"Albania"},
{ dial: "213", code: "DZ", name:"Algeria"},
{ dial: "1684", code: "AS", name:"American Samoa"},
{ dial: "376", code: "AD", name:"Andorra"},
{ dial: "244", code: "AO", name:"Angola"},
{ dial: "1264", code: "AI", name:"Anguilla"},
{ dial: "672", code: "AQ", name:"Antarctica"},
{ dial: "1268", code: "AG", name:"Antigua &amp; Barbuda"},
{ dial: "54", code: "AR", name:"Argentina"},
{ dial: "374", code: "AM", name:"Armenia"},
{ dial: "297", code: "AW", name:"Aruba"},
{ dial: "61", code: "AU", name:"Australia"},
{ dial: "43", code: "AT", name:"Austria"},
{ dial: "994", code: "AZ", name:"Azerbaijan"},
{ dial: "242", code: "BS", name:"Bahama"},
{ dial: "973", code: "BH", name:"Bahrain"},
{ dial: "880", code: "BD", name:"Bangladesh"},
{ dial: "1246", code: "BB", name:"Barbados"},
{ dial: "375", code: "BY", name:"Belarus"},
{ dial: "32", code: "BE", name:"Belgium"},
{ dial: "501", code: "BZ", name:"Belize"},
{ dial: "229", code: "BJ", name:"Benin"},
{ dial: "1441", code: "BM", name:"Bermuda"},
{ dial: "975", code: "BT", name:"Bhutan"},
{ dial: "591", code: "BO", name:"Bolivia"},
{ dial: "387", code: "BA", name:"Bosnia and Herzegovina"},
{ dial: "267", code: "BW", name:"Botswana"},
{ dial: "NULL", code: "BV", name:"Bouvet Island"},
{ dial: "55", code: "BR", name:"Brazil"},
{ dial: "246", code: "IO", name:"British Indian Ocean Territory"},
{ dial: "1284", code: "VG", name:"British Virgin Islands"},
{ dial: "673", code: "BN", name:"Brunei Darussalam"},
{ dial: "359", code: "BG", name:"Bulgaria"},
{ dial: "226", code: "BF", name:"Burkina Faso"},
{ dial: "257", code: "BI", name:"Burundi"},
{ dial: "855", code: "KH", name:"Cambodia"},
{ dial: "237", code: "CM", name:"Cameroon"},
{ dial: "1", code: "CA", name:"Canada"},
{ dial: "238", code: "CV", name:"Cape Verde"},
{ dial: "1345", code: "KY", name:"Cayman Islands"},
{ dial: "236", code: "CF", name:"Central African Republic"},
{ dial: "235", code: "TD", name:"Chad"},
{ dial: "56", code: "CL", name:"Chile"},
{ dial: "86", code: "CN", name:"China"},
{ dial: "61", code: "CX", name:"Christmas Island"},
{ dial: "61", code: "CC", name:"Cocos (Keeling) Islands"},
{ dial: "57", code: "CO", name:"Colombia"},
{ dial: "269", code: "KM", name:"Comoros"},
{ dial: "242", code: "CG", name:"Congo"},
{ dial: "243", code: "CD", name:"Congo, Democratic Republic"},
{ dial: "682", code: "CK", name:"Cook Iislands"},
{ dial: "506", code: "CR", name:"Costa Rica"},
{ dial: "225", code: "CI", name:"Côte D'ivoire (Ivory Coast)"},
{ dial: "385", code: "HR", name:"Croatia"},
{ dial: "53", code: "CU", name:"Cuba"},
{ dial: "357", code: "CY", name:"Cyprus"},
{ dial: "420", code: "CZ", name:"Czech Republic"},
{ dial: "45", code: "DK", name:"Denmark"},
{ dial: "253", code: "DJ", name:"Djibouti"},
{ dial: "1767", code: "DM", name:"Dominica"},
{ dial: "1809", code: "DO", name:"Dominican Republic"},
{ dial: "670", code: "TP", name:"East Timor"},
{ dial: "593", code: "EC", name:"Ecuador"},
{ dial: "20", code: "EG", name:"Egypt"},
{ dial: "503", code: "SV", name:"El Salvador"},
{ dial: "240", code: "GQ", name:"Equatorial Guinea"},
{ dial: "291", code: "ER", name:"Eritrea"},
{ dial: "372", code: "EE", name:"Estonia"},
{ dial: "251", code: "ET", name:"Ethiopia"},
{ dial: "389", code: "MK", name:"F.Y.R.O.M. (Macedonia)"},
{ dial: "500", code: "FK", name:"Falkland Islands (Malvinas)"},
{ dial: "298", code: "FO", name:"Faroe Islands"},
{ dial: "679", code: "FJ", name:"Fiji"},
{ dial: "358", code: "FI", name:"Finland"},
{ dial: "33", code: "FR", name:"France"},
{ dial: "", code: "FX", name:"France, Metropolitan"},
{ dial: "594", code: "GF", name:"French Guiana"},
{ dial: "689", code: "PF", name:"French Polynesia"},
{ dial: "", code: "TF", name:"French Southern Territories"},
{ dial: "241", code: "GA", name:"Gabon"},
{ dial: "220", code: "GM", name:"Gambia"},
{ dial: "995", code: "GE", name:"Georgia"},
{ dial: "49", code: "DE", name:"Germany"},
{ dial: "233", code: "GH", name:"Ghana"},
{ dial: "350", code: "GI", name:"Gibraltar"},
{ dial: "30", code: "GR", name:"Greece"},
{ dial: "299", code: "GL", name:"Greenland"},
{ dial: "1473", code: "GD", name:"Grenada"},
{ dial: "590", code: "GP", name:"Guadeloupe"},
{ dial: "1671", code: "GU", name:"Guam"},
{ dial: "502", code: "GT", name:"Guatemala"},
{ dial: "224", code: "GN", name:"Guinea"},
{ dial: "245", code: "GW", name:"Guinea-Bissau"},
{ dial: "592", code: "GY", name:"Guyana"},
{ dial: "509", code: "HT", name:"Haiti"},
{ dial: "", code: "HM", name:"Heard &amp; McDonald Islands"},
{ dial: "504", code: "HN", name:"Honduras"},
{ dial: "852", code: "HK", name:"Hong Kong"},
{ dial: "36", code: "HU", name:"Hungary"},
{ dial: "354", code: "IS", name:"Iceland"},
{ dial: "91", code: "IN", name:"India"},
{ dial: "62", code: "ID", name:"Indonesia"},
{ dial: "964", code: "IQ", name:"Iraq"},
{ dial: "353", code: "IE", name:"Ireland"},
{ dial: "98", code: "IR", name:"Islamic Republic of Iran"},
{ dial: "972", code: "IL", name:"Israel"},
{ dial: "39", code: "IT", name:"Italy"},
{ dial: "1876", code: "JM", name:"Jamaica"},
{ dial: "81", code: "JP", name:"Japan"},
{ dial: "962", code: "JO", name:"Jordan"},
{ dial: "7", code: "KZ", name:"Kazakhstan"},
{ dial: "254", code: "KE", name:"Kenya"},
{ dial: "686", code: "KI", name:"Kiribati"},
{ dial: "850", code: "KP", name:"Korea, Democratic People's Republic of"},
{ dial: "82", code: "KR", name:"Korea, Republic of"},
{ dial: "965", code: "KW", name:"Kuwait"},
{ dial: "996", code: "KG", name:"Kyrgyzstan"},
{ dial: "856", code: "LA", name:"Lao People's Democratic Republic"},
{ dial: "371", code: "LV", name:"Latvia"},
{ dial: "961", code: "LB", name:"Lebanon"},
{ dial: "266", code: "LS", name:"Lesotho"},
{ dial: "231", code: "LR", name:"Liberia"},
{ dial: "218", code: "LY", name:"Libyan Arab Jamahiriya"},
{ dial: "423", code: "LI", name:"Liechtenstein"},
{ dial: "370", code: "LT", name:"Lithuania"},
{ dial: "352", code: "LU", name:"Luxembourg"},
{ dial: "853", code: "MO", name:"Macau"},
{ dial: "261", code: "MG", name:"Madagascar"},
{ dial: "265", code: "MW", name:"Malawi"},
{ dial: "60", code: "MY", name:"Malaysia"},
{ dial: "960", code: "MV", name:"Maldives"},
{ dial: "223", code: "ML", name:"Mali"},
{ dial: "356", code: "MT", name:"Malta"},
{ dial: "692", code: "MH", name:"Marshall Islands"},
{ dial: "596", code: "MQ", name:"Martinique"},
{ dial: "222", code: "MR", name:"Mauritania"},
{ dial: "230", code: "MU", name:"Mauritius"},
{ dial: "262", code: "YT", name:"Mayotte"},
{ dial: "52", code: "MX", name:"Mexico"},
{ dial: "691", code: "FM", name:"Micronesia"},
{ dial: "373", code: "MD", name:"Moldova, Republic of"},
{ dial: "377", code: "MC", name:"Monaco"},
{ dial: "976", code: "MN", name:"Mongolia"},
{ dial: "664", code: "MS", name:"Monserrat"},
{ dial: "382", code: "ME", name:"Montenegro "},
{ dial: "212", code: "MA", name:"Morocco"},
{ dial: "258", code: "MZ", name:"Mozambique"},
{ dial: "95", code: "MM", name:"Myanmar"},
{ dial: "264", code: "NA", name:"Namibia"},
{ dial: "674", code: "NR", name:"Nauru"},
{ dial: "977", code: "NP", name:"Nepal"},
{ dial: "31", code: "NL", name:"Netherlands"},
{ dial: "599", code: "AN", name:"Netherlands Antilles"},
{ dial: "687", code: "NC", name:"New Caledonia"},
{ dial: "64", code: "NZ", name:"New Zealand"},
{ dial: "505", code: "NI", name:"Nicaragua"},
{ dial: "227", code: "NE", name:"Niger"},
{ dial: "234", code: "NG", name:"Nigeria"},
{ dial: "683", code: "NU", name:"Niue"},
{ dial: "672", code: "NF", name:"Norfolk Island"},
{ dial: "1670", code: "MP", name:"Northern Mariana Islands"},
{ dial: "47", code: "NO", name:"Norway"},
{ dial: "968", code: "OM", name:"Oman"},
{ dial: "", code: "OT", name:"Other"},
{ dial: "92", code: "PK", name:"Pakistan"},
{ dial: "680", code: "PW", name:"Palau"},
{ dial: "", code: "PS", name:"Palestinian Territory, Occupied"},
{ dial: "507", code: "PA", name:"Panama"},
{ dial: "675", code: "PG", name:"Papua New Guinea"},
{ dial: "595", code: "PY", name:"Paraguay"},
{ dial: "51", code: "PE", name:"Peru"},
{ dial: "63", code: "PH", name:"Philippines"},
{ dial: "870", code: "PN", name:"Pitcairn"},
{ dial: "48", code: "PL", name:"Poland"},
{ dial: "351", code: "PT", name:"Portugal"},
{ dial: "1", code: "PR", name:"Puerto Rico"},
{ dial: "974", code: "QA", name:"Qatar"},
{ dial: "", code: "RE", name:"Réunion"},
{ dial: "40", code: "RO", name:"Romania"},
{ dial: "7", code: "RU", name:"Russian Federation"},
{ dial: "250", code: "RW", name:"Rwanda"},
{ dial: "590", code: "BL", name:"Saint Barthelemy"},
{ dial: "1758", code: "LC", name:"Saint Lucia"},
{ dial: "1599", code: "MF", name:"Saint Martin"},
{ dial: "685", code: "WS", name:"Samoa"},
{ dial: "378", code: "SM", name:"San Marino"},
{ dial: "239", code: "ST", name:"Sao Tome & Principe"},
{ dial: "966", code: "SA", name:"Saudi Arabia"},
{ dial: "221", code: "SN", name:"Senegal"},
{ dial: "381", code: "RS", name:"Serbia"},
{ dial: "248", code: "SC", name:"Seychelles"},
{ dial: "232", code: "SL", name:"Sierra Leone"},
{ dial: "65", code: "SG", name:"Singapore"},
{ dial: "421", code: "SK", name:"Slovakia"},
{ dial: "386", code: "SI", name:"Slovenia"},
{ dial: "677", code: "SB", name:"Solomon Islands"},
{ dial: "252", code: "SO", name:"Somalia"},
{ dial: "27", code: "ZA", name:"South Africa"},
{ dial: "", code: "GS", name:"South Georgia and the South Sandwich Islands"},
{ dial: "34", code: "ES", name:"Spain"},
{ dial: "94", code: "LK", name:"Sri Lanka"},
{ dial: "290", code: "SH", name:"St. Helena"},
{ dial: "1869", code: "KN", name:"St. Kitts and Nevis"},
{ dial: "508", code: "PM", name:"St. Pierre &amp; Miquelon"},
{ dial: "1784", code: "VC", name:"St. Vincent &amp; the Grenadines"},
{ dial: "249", code: "SD", name:"Sudan"},
{ dial: "597", code: "SR", name:"Suriname"},
{ dial: "", code: "SJ", name:"Svalbard &amp; Jan Mayen Islands"},
{ dial: "268", code: "SZ", name:"Swaziland"},
{ dial: "46", code: "SE", name:"Sweden"},
{ dial: "41", code: "CH", name:"Switzerland"},
{ dial: "963", code: "SY", name:"Syrian Arab Republic"},
{ dial: "886", code: "TW", name:"Taiwan, Province of China"},
{ dial: "992", code: "TJ", name:"Tajikistan"},
{ dial: "255", code: "TZ", name:"Tanzania, United Republic of"},
{ dial: "66", code: "TH", name:"Thailand"},
{ dial: "670", code: "TL", name:"Timor-Leste"},
{ dial: "228", code: "TG", name:"Togo"},
{ dial: "690", code: "TK", name:"Tokelau"},
{ dial: "676", code: "TO", name:"Tonga"},
{ dial: "1868", code: "TT", name:"Trinidad &amp; Tobago"},
{ dial: "216", code: "TN", name:"Tunisia"},
{ dial: "90", code: "TR", name:"Turkey"},
{ dial: "993", code: "TM", name:"Turkmenistan"},
{ dial: "1649", code: "TC", name:"Turks &amp; Caicos Islands"},
{ dial: "688", code: "TV", name:"Tuvalu"},
{ dial: "256", code: "UG", name:"Uganda"},
{ dial: "380", code: "UA", name:"Ukraine"},
{ dial: "971", code: "AE", name:"United Arab Emirates"},
{ dial: "44", code: "UK", name:"United Kingdom"},
{ dial: "44", code: "GB", name:"United Kingdom (Great Britain)"},
{ dial: "", code: "UM", name:"United States Minor Outlying Islands"},
{ dial: "1", code: "US", name:"United States of America"},
{ dial: "1340", code: "VI", name:"United States Virgin Islands"},
{ dial: "598", code: "UY", name:"Uruguay"},
{ dial: "998", code: "UZ", name:"Uzbekistan"},
{ dial: "678", code: "VU", name:"Vanuatu"},
{ dial: "39", code: "VA", name:"Vatican City State (Holy See)"},
{ dial: "58", code: "VE", name:"Venezuela"},
{ dial: "84", code: "VN", name:"Viet Nam"},
{ dial: "681", code: "WF", name:"Wallis &amp; Futuna Islands"},
{ dial: "212", code: "EH", name:"Western Sahara"},
{ dial: "967", code: "YE", name:"Yemen"},
{ dial: "381", code: "YU", name:"Yugoslavia"},
{ dial: "260", code: "ZM", name:"Zambia"},
{ dial: "263", code: "ZW", name:"Zimbabwe"},
]

const FLIGHT_CODE_OPTIONS: Object[] = [
  {value: "0", display: {
    "en-gb": "Not Applicable",
    "ko-kr": "기타",
    "ja-jp": "不明",
    "ms-my": "Tidak Berkenaan",
    "id-id": "Tidak Berlaku",
    "zh-cn": "不适用",
    "zh-hk": "不適用",
    "th-th": "ไม่ระบุเที่ยวบิน"
    }
  },
  {value: "1", display: "AK"},
  {value: "2", display: "D7"},
  {value: "3", display: "FD"},
  {value: "4", display: "QZ"},
  {value: "8", display: "Z2"},
  {value: "9", display: "I5"},
  {value: "10", display: "XJ"},
  {value: "11", display: "XT"},
  {value: "12", display: "DJ"}
]

const TYPE_OPTIONS: Object = {
  "en-gb": {
    9: [
      {display: "About AirAsia", value: "88"},
      {display: "Personnel", value: "87"}
    ],
    4: [
      {display: "About AirAsia", value: "89"},
      {display: "Big Loyalty Programme", value: "90"},
      {display: "Baggage", value: "95"},
      {display: "Duty Free", value: "107"},
      {display: "Payment", value: "92"},
      {display: "Product & Services", value: "93"},
      {display: "Sales", value: "94"},
      {display: "Traveler Guide", value: "91"},
    ],
    12: [
      {display: "AirAsia Insure", value: "519"},
      {display: "Document Request", value: "520"},
      {display: "Member Email Change", value: "106"},
      {display: "Modify Booking", value: "104"},
      {display: "New Booking", value: "102"},
      {display: "Preflight", value: "105"},
    ],
    1: [
      {display: "Airport & Transportation", value: "79"},
      {display: "Big Loyalty Programme", value: "81"},
      {display: "Baggage", value: "10"},
      {display: "Customer Service", value: "77"},
      {display: "Duty Free", value: "108"},
      {display: "Flight Schedule & Safety", value: "78"},
      {display: "In-flight Services & Products", value: "80"},
      {display: "Manage My Booking / Check In", value: "82"},
      {display: "New Booking", value: "83"},
      {display: "Payment", value: "84"},
      {display: "Personnel", value: "85"},
      {display: "Refund Request", value: "86"},
    ],
    8: [
      {display: "Airport Tax", value: "245"},
      {display: "Double Payment", value: "250"},
      {display: "Duplicate Booking", value: "249"},
      {display: "Duty Free", value: "109"},
      {display: "Flight Cancellation", value: "511"},
      {display: "Flight Reschedule", value: "513"}
    ]
  },
  "ko-kr": {
    9: [
      {display: "AirAsia에 관하여", value: "88"},
      {display: "직원", value: "87"}
    ],
    4: [
      {display: "AirAsia에 관하여", value: "89"},
      {display: "Big Loyalty Programme", value: "90"},
      {display: "수하물", value: "95"},
      {display: "면세", value: "107"},
      {display: "결제", value: "92"},
      {display: "상품 및 서비스", value: "93"},
      {display: "판매", value: "94"},
      {display: "여행자 가이드", value: "91"},
    ],
    12: [
      {display: "AirAsia Insure", value: "519"},
      {display: "서류 요청", value: "520"},
      {display: "회원 이메일 변경", value: "106"},
      {display: "예약 수정", value: "104"},
      {display: "신규 예약", value: "102"},
      {display: "출발 전 변경사항", value: "105"},
    ],
    1: [
      {display: "공항 및 교통", value: "79"},
      {display: "Big Loyalty Programme", value: "81"},
      {display: "수하물", value: "10"},
      {display: "고객 서비스", value: "77"},
      {display: "면세", value: "108"},
      {display: "항공편 일정 및 안전", value: "78"},
      {display: "기내 서비스 및 상품", value: "80"},
      {display: "나의 예약 관리 / 체크인", value: "82"},
      {display: "신규 예약", value: "83"},
      {display: "결제", value: "84"},
      {display: "직원", value: "85"},
      {display: "환불 요청", value: "86"},
    ],
    8: [
      {display: "공항세", value: "245"},
      {display: "이중 결제", value: "250"},
      {display: "중복예약", value: "249"},
      {display: "면세", value: "109"},
      {display: "결항편", value: "511"},
      {display: "출발시각변경편", value: "513"}
    ]
  },
  "ja-jp": {
    9: [
      {display: "エアアジアについて", value: "88"},
      {display: "スタッフについて", value: "87"}
    ],
    4: [
      {display: "エアアジアについて", value: "89"},
      {display: "Big Loyalty Programme", value: "90"},
      {display: "手荷物", value: "95"},
      {display: "免税品", value: "107"},
      {display: "支払い", value: "92"},
      {display: "商品＆サービス", value: "93"},
      {display: "販売", value: "94"},
      {display: "トラベルガイド", value: "91"},
    ],
    12: [
      {display: "AirAsia Insure(エアアジア旅行保険)", value: "519"},
      {display: "証明書・書類請求", value: "520"},
      {display: "会員のEメールアドレス変更", value: "106"},
      {display: "予約の変更", value: "104"},
      {display: "新しい予約", value: "102"},
      {display: "飛行前", value: "105"},
    ],
    1: [
      {display: "空港と交通手段", value: "79"},
      {display: "Big Loyalty Programme", value: "81"},
      {display: "手荷物", value: "10"},
      {display: "カスタマーサービス", value: "77"},
      {display: "免税品", value: "108"},
      {display: "フライトスケジュール＆安全について", value: "78"},
      {display: "機内サービス＆商品", value: "80"},
      {display: "マイ・ブッキング/チェックイン", value: "82"},
      {display: "新しい予約", value: "83"},
      {display: "支払い", value: "84"},
      {display: "スタッフについて", value: "85"},
      {display: "払い戻しのリクエスト", value: "86"},
    ],
    8: [
      {display: "空港税", value: "245"},
      {display: "二重支払い", value: "250"},
      {display: "重複予約", value: "249"},
      {display: "免税品", value: "109"},
      {display: "欠航便", value: "511"},
      {display: "出発時刻変更便", value: "513"}
    ]
  },
  "ms-my": {
    9: [
      {display: "Tentang AirAsia", value: "88"},
      {display: "Kakitangan", value: "87"}
    ],
    4: [
      {display: "Tentang AirAsia", value: "89"},
      {display: "Big Loyalty Programme", value: "90"},
      {display: "Bagasi", value: "95"},
      {display: "Barang Bebas Cukai", value: "107"},
      {display: "Pembayaran", value: "92"},
      {display: "Produk & perkhidmatan", value: "93"},
      {display: "Jualan", value: "94"},
      {display: "Panduan Perjalanan Untuk Penumpang", value: "91"},
    ],
    12: [
      {display: "AirAsia Insure", value: "519"},
      {display: "Permintaan dokumen", value: "520"},
      {display: "Perubahan E-mel Ahli", value: "106"},
      {display: "Ubah suai tempahan", value: "104"},
      {display: "Tempahan baru", value: "102"},
      {display: "Preflight", value: "105"},
    ],
    1: [
      {display: "Lapangan terbang dan pengangkutan", value: "79"},
      {display: "Big Loyalty Programme", value: "81"},
      {display: "Bagasi", value: "10"},
      {display: "Khidmat pelanggan", value: "77"},
      {display: "Barang Bebas Cukai", value: "108"},
      {display: "Jadual penerbangan & keselamatan", value: "78"},
      {display: "Perkhidmatan & produk dalam penerbangan", value: "80"},
      {display: "Urus Tempahan Saya / Daftar Masuk", value: "82"},
      {display: "Tempahan baru", value: "83"},
      {display: "Pembayaran", value: "84"},
      {display: "Kakitangan", value: "85"},
      {display: "Permohonan bayaran balik", value: "86"},
    ],
    8: [
      {display: "Cukai lapangan terbang", value: "245"},
      {display: "Pembayaran dua kali", value: "250"},
      {display: "Tempahan Berganda", value: "249"},
      {display: "Barang Bebas Cukai", value: "109"},
      {display: "Pembatalan Penerbangan", value: "511"},
      {display: "Perubahan Jadual Penerbangan", value: "513"}
    ]
  },
  "id-id": {
    9: [
      {display: "Tentang AirAsia", value: "88"},
      {display: "Personil", value: "87"}
    ],
    4: [
      {display: "Tentang AirAsia", value: "89"},
      {display: "Big Loyalty Programme", value: "90"},
      {display: "Bagasi", value: "95"},
      {display: "Duty Free", value: "107"},
      {display: "Pembayaran", value: "92"},
      {display: "Produk & layanan", value: "93"},
      {display: "Penjualan", value: "94"},
      {display: "Panduan Penumpang", value: "91"},
    ],
    12: [
      {display: "AirAsia Insure", value: "519"},
      {display: "Permintaan dokumen", value: "520"},
      {display: "Perubahan Email Anggota", value: "106"},
      {display: "Perubahan Pemesanan Penerbangan", value: "104"},
      {display: "Pemesanan baru", value: "102"},
      {display: "Preflight", value: "105"},
    ],
    1: [
      {display: "Bandara dan transportasi", value: "79"},
      {display: "Big Loyalty Programme", value: "81"},
      {display: "Bagasi", value: "10"},
      {display: "Layanan pelanggan", value: "77"},
      {display: "Bebas pajak", value: "108"},
      {display: "Jadwal penerbangan dan keamanan", value: "78"},
      {display: "Layanan dan produk di dalam pesawat", value: "80"},
      {display: "Mengatur Pembelian Saya / Check-In", value: "82"},
      {display: "Pemesanan baru", value: "83"},
      {display: "Pembayaran", value: "84"},
      {display: "Personil", value: "85"},
      {display: "Permintaan refund", value: "86"},
    ],
    8: [
      {display: "Pajak bandara", value: "245"},
      {display: "Pembayaran Ganda", value: "250"},
      {display: "Pemesanan Ganda", value: "249"},
      {display: "Bebas pajak", value: "109"},
      {display: "Penerbangan dibatalkan", value: "511"},
      {display: "Penerbangan Berubah Jadwal", value: "513"}
    ]
  },
  "zh-cn": {
    9: [
      {display: "关于亚航", value: "88"},
      {display: "人员", value: "87"}
    ],
    4: [
      {display: "关于亚航", value: "89"},
      {display: "Big Loyalty Programme", value: "90"},
      {display: "行李", value: "95"},
      {display: "免税", value: "107"},
      {display: "付款", value: "92"},
      {display: "产品及服务", value: "93"},
      {display: "销售", value: "94"},
      {display: "旅客指南", value: "91"},
    ],
    12: [
      {display: "AirAsia Insure", value: "519"},
      {display: "文件要求", value: "520"},
      {display: "会员电子邮件更改", value: "106"},
      {display: "修改预订", value: "104"},
      {display: "新预订", value: "102"},
      {display: "登机前", value: "105"},
    ],
    1: [
      {display: "机场及交通", value: "79"},
      {display: "Big Loyalty Programme", value: "81"},
      {display: "行李", value: "10"},
      {display: "客户服务", value: "77"},
      {display: "免税", value: "108"},
      {display: "航班时刻表及安全", value: "78"},
      {display: "机上服务及产品", value: "80"},
      {display: "管理我的预订/办理登机手续", value: "82"},
      {display: "新预订", value: "83"},
      {display: "付款", value: "84"},
      {display: "人员", value: "85"},
      {display: "退款要求", value: "86"},
    ],
    8: [
      {display: "机场税", value: "245"},
      {display: "重复付款", value: "250"},
      {display: "重复预订", value: "249"},
      {display: "免税", value: "109"},
      {display: "航班取消", value: "511"},
      {display: "航班调整", value: "513"}
    ]
  },
  "zh-hk": {
    9: [
      {display: "關於亞航", value: "88"},
      {display: "服務人員", value: "87"}
    ],
    4: [
      {display: "關於亞航", value: "89"},
      {display: "Big Loyalty Programme", value: "90"},
      {display: "行李", value: "95"},
      {display: "免稅購物", value: "107"},
      {display: "付款", value: "92"},
      {display: "產品及服務", value: "93"},
      {display: "銷售", value: "94"},
      {display: "旅客指南", value: "91"},
    ],
    12: [
      {display: "AirAsia Insure", value: "519"},
      {display: "要求文件", value: "520"},
      {display: "會員電郵變更", value: "106"},
      {display: "更改預訂", value: "104"},
      {display: "新的預訂", value: "102"},
      {display: "起飛前", value: "105"},
    ],
    1: [
      {display: "機場及交通", value: "79"},
      {display: "Big Loyalty Programme", value: "81"},
      {display: "行李", value: "10"},
      {display: "客戶服務", value: "77"},
      {display: "免稅購物", value: "108"},
      {display: "航班時間表及安全", value: "78"},
      {display: "機上服務及產品", value: "80"},
      {display: "管理我的訂位 / 登機手續", value: "82"},
      {display: "新的預訂", value: "83"},
      {display: "付款", value: "84"},
      {display: "服務人員", value: "85"},
      {display: "退款要求", value: "86"},
    ],
    8: [
      {display: "機場稅", value: "245"},
      {display: "雙重付款", value: "250"},
      {display: "重複預訂", value: "249"},
      {display: "免稅購物", value: "109"},
      {display: "航班取消", value: "511"},
      {display: "航班調整", value: "513"}
    ]
  },
  "th-th": {
    9: [
      {display: "เกี่ยวกับ AirAsia", value: "88"},
      {display: "บุคลากร", value: "87"}
    ],
    4: [
      {display: "เกี่ยวกับ AirAsia", value: "89"},
      {display: "BIG CARD บัตรสะสมคะแนน", value: "90"},
      {display: "สัมภาระ", value: "95"},
      {display: "ปลอดภาษี", value: "107"},
      {display: "การชำระเงิน", value: "92"},
      {display: "ผลิตภัณฑ์และบริการ", value: "93"},
      {display: "ฝ่ายขาย", value: "94"},
      {display: "คู่มือการเดินทาง", value: "91"},
    ],
    12: [
      {display: "แอร์เอเชียอินชัวร์", value: "519"},
      {display: "การแจ้งขอเอกสาร", value: "520"},
      {display: "สมาชิกเปลี่ยนอีเมล", value: "106"},
      {display: "การแก้ไขรายการจอง", value: "104"},
      {display: "รายการจองใหม่", value: "102"},
      {display: "ก่อนออกบิน", value: "105"},
    ],
    1: [
      {display: "สนามบินและการเดินทาง", value: "79"},
      {display: "BIG CARD บัตรสะสมคะแนน", value: "81"},
      {display: "สัมภาระ", value: "10"},
      {display: "บริการลูกค้า", value: "77"},
      {display: "ปลอดภาษี", value: "108"},
      {display: "ตารางบินและความปลอดภัย", value: "78"},
      {display: "บริการและผลิตภัณฑ์บนเที่ยวบิน", value: "80"},
      {display: "จัดการบุ๊กกิ้ง / เช็คอิน", value: "82"},
      {display: "รายการจองใหม่", value: "83"},
      {display: "การชำระเงิน", value: "84"},
      {display: "บุคลากร", value: "85"},
      {display: "ขอเงินคืน", value: "86"},
    ],
    8: [
      {display: "ภาษีสนามบิน", value: "245"},
      {display: "จ่ายเงินซ้อน", value: "250"},
      {display: "หมายเลขการสำรองที่นั่งซ้ำซ้อน", value: "249"},
      {display: "ปลอดภาษี", value: "109"},
      {display: "เที่ยวบินยกเลิก", value: "511"},
      {display: "เที่ยวบินเปลี่ยนเวลา", value: "513"}
    ]
  }
}

const CASE_OPTIONS: Object = {
  "en-gb": [{display: "Compliment", value: "9"}, {display: "Enquiry", value: "1"}, {display: "Customer Request", value: "12"}, {display: "Complaints", value: "1"}, {display: "Refund", value: "8"}],
  "ko-kr": [{display: "칭찬", value: "9"}, {display: "문의", value: "1"}, {display: "고객 요청", value: "12"}, {display: "불편사항", value: "1"}, {display: "환불", value: "8"}],
  "ja-jp": [{display: "お褒めの言葉", value: "9"}, {display: "お問い合わせ", value: "1"}, {display: "ご要望", value: "12"}, {display: "クレーム・ご意見", value: "1"}, {display: "払い戻し", value: "8"}],
  "ms-my": [{display: "Pujian", value: "9"}, {display: "Pertanyaan", value: "1"}, {display: "Permintaan pelanggan", value: "12"}, {display: "Aduan", value: "1"}, {display: "Pemulangan bayaran", value: "8"}],
  "id-id": [{display: "Komplimen", value: "9"}, {display: "Pertanyaan", value: "1"}, {display: "Permintaan pelanggan", value: "12"}, {display: "Keluhan", value: "1"}, {display: "Refund", value: "8"}],
  "zh-cn": [{display: "表扬", value: "9"}, {display: "咨询", value: "1"}, {display: "乘客要求", value: "12"}, {display: "投诉", value: "1"}, {display: "退款", value: "8"}],
  "zh-hk": [{display: "致意", value: "9"}, {display: "詢問", value: "1"}, {display: "乘客要求", value: "12"}, {display: "投訴", value: "1"}, {display: "退款", value: "8"}],
  "th-th": [{display: "ชมเชย", value: "9"}, {display: "สอบถามข้อมูล", value: "1"}, {display: "การแจ้งขอจากลูกค้า", value: "12"}, {display: "ข้อร้องเรียน", value: "1"}, {display: "การคืนเงิน", value: "8"}]
}

const LABELS: Object = {
  "en-gb":{
    name: {main: "First and Last name", err: ["Please fill in first name", "Please fill in last name"]},
    email: {main: "Email Address", err: "Please fill in email"},
    mobilenum: {main: "Mobile phone number", err: "Mobile phone number should include international dialing code with only number from 0 to 9. ('space', '-', '+' and other non-decimal characters are not allowed)"},
    homenum: {main: "Home phone number", err: ""},
    casecategory: {main: "Case category", err: "Please select your case category"},
    typecategory: {main: "Type", err: "Please select your case type"},
    bookingnumber: {main: "Booking number", err: "Please fill in your booking number for refund verification"},
    flightnumber: {main: "Flight number", err: ["Please select airline code", "Please fill in flight number"]},
    flightdatetime: {main: "Flight date and time", err: ""},
    attachment: {main: "Attachment", err: ""},
    feedback: {main: "Feedback", err: "Please fill in feedback", extra: "Please indicate if you would like to request for a full refund (all sectors) or the affected sector only."},
    paymentmethod: {main: "Booking Payment", err: "", extra: "This refund will be made to the initial credit card account used during booking, thus the following fields can be disregarded."},
    bankname: {main: "Bank Name", err: "Please fill in bank name"},
    bankholdername: {main: "Bank Account Holder's Name", err: "Please fill in only alphabets (a-z) for bank account holder's name"},
    bankaccountnumber: {main: "Bank Account Number", err: "Please fill in bank account number"},
    bankbranch: {main: "Bank Branch", err: "Please fill in bank branch"},
    bankcurrency: {main: "Bank Currency", err: "Please select bank currency"},
    bankroutecode: {main: "International Bank Code", err: "Please select routing code"},
    bankroutenumber: {main: "International Bank Number", err: "Please fill in routing code number"},
    button: {reset: "Clear", submit: "Submit"}
  },
  "ko-kr":{
    name: {main: "이름", err: ["성을 입력하세요", "성을 입력하세요"]},
    email: {main: "이메일 주소", err: "이메일 주소를 입력하세요"},
    mobilenum: {main: "휴대폰 번호", err: "휴대전화 번호에는 국제 전화코드가 포함되어야 하며 0~9의 숫자만을 입력해야 합니다. ('공백', '-', '+' 및 숫자가 아닌 문자는 허용되지 않습니다)"},
    homenum: {main: "집 전화 번호", err: ""},
    casecategory: {main: "사례 분류", err: "문의하실 항목을 선택해주시기 바랍니다"},
    typecategory: {main: "유형", err: "질문의 종류를 선택해주시기 바랍니다"},
    bookingnumber: {main: "예약 번호", err: ""},
    flightnumber: {main: "비행편 번호", err: ["항공사 코드를 선택하십시오", "항공편 번호를 입력하세요"]},
    flightdatetime: {main: "비행 일자 및 시간", err: ""},
    attachment: {main: "첨부파일", err: ""},
    feedback: {main: "피드백", err: "피드백을 입력하세요", extra: "귀하의 환불진행을 위하여 전 구간 또는 피해 받은 구간 중 선택하여주시기 바랍니다"},
    paymentmethod: {main: "결제수단", err: "", extra: "예약하실 때 최초로 결제하신 신용카드로 카드취소 되실 예정이므로 아래의 사항들은 작성하시지 마십시오"},
    bankname: {main: "은행명", err: "은행 이름을 입력해 주세요"},
    bankholdername: {main: "은행 계좌 소유자 이름", err: "은행 예금주의 이름을 알파벳 (A-Z)으로 작성하십시오"},
    bankaccountnumber: {main: "은행 계좌번호", err: "계좌번호를 입력해 주세요"},
    bankbranch: {main: "은행 지점", err: "지점 이름을 입력해 주세요"},
    bankcurrency: {main: "은행 통화", err: "은행 통화란을 작성해 주십시오"},
    bankroutecode: {main: "국제은행코드", err: "은행식별코드(Routing Code)를 입력해 주세요"},
    bankroutenumber: {main: "국제은행번호", err: "은행식별코드(Routing Code)번호를 입력해 주세요"},
    button: {reset: "삭제", submit: "제출"}
  },
  "ja-jp":{
    name: {main: "氏名（ローマ字でご入力下さい）", err: ["お名前を入力してください", "名字を入力してください"]},
    email: {main: "Eメールアドレス", err: "Eメールアドレスを入力してください"},
    mobilenum: {main: "携帯電話番号", err: "携帯電話番号には国番号（0～9の数字のみ使用可）を付けてください（スペース、「-」、「+」や数字以外の文字は使用できません）"},
    homenum: {main: "自宅電話番号", err: ""},
    casecategory: {main: "問題の種類", err: "お問い合わせの項目をお選びください"},
    typecategory: {main: "種類", err: "＊お問い合わせの種類をお選びください"},
    bookingnumber: {main: "予約番号", err: ""},
    flightnumber: {main: "フライト番号", err: ["航空会社のコードを選択してください", "便名を入力してください"]},
    flightdatetime: {main: "フライト日時", err: ""},
    attachment: {main: "添付", err: ""},
    feedback: {main: "ご意見（日本語入力可", err: "ご意見を入力してください", extra: "往路・復路合わせての払い戻し、または影響の生じた路線のみの払い戻しをご希望の際は、こちらにご記入ください"},
    paymentmethod: {main: "予約時にご利用になられた支払い方法", err: "", extra: "この払い戻しは、予約時に使用された最初のクレジットカードに行われますので、以下の項目に入力する必要はありません"},
    bankname: {main: "銀行名", err: "銀行名をご記入ください"},
    bankholdername: {main: "口座名義人名", err: "口座所有者を英字（a-z）のみで記入してください"},
    bankaccountnumber: {main: "銀行の口座番号", err: "銀行口座番号をご記入ください"},
    bankbranch: {main: "銀行の支店", err: "銀行支店名をご記入ください"},
    bankcurrency: {main: "銀行通貨", err: "銀行の通貨をご記入ください"},
    bankroutecode: {main: "金融機関識別コード種別", err: "ルーティングコードをご記入ください"},
    bankroutenumber: {main: "金融機関識別コード", err: "ルーティングコード番号をご記入ください"},
    button: {reset: "クリア", submit: "送信"}
  },
  "ms-my":{
    name: {main: "Nama Pertama dan Keluarga", err: ["Sila isikan Nama Pertama","Sila isikan Nama Keluarga"]},
    email: {main: "Alamat E-mel", err: "Sila isikan Alamat E-mel"},
    mobilenum: {main: "Nombor telefon bimbit", err: "Nombor telefon bimbit hendaklah merangkumi kod panggilan antarabangsa dengan nombor sahaja daripada 0 hingga 9. ('jarak', '-', '+' aksara bukan nombor yang lain tidak dibenarkan)"},
    homenum: {main: "Nombor telefon rumah", err: ""},
    casecategory: {main: "Kategori kes", err: ""},
    typecategory: {main: "Jenis", err: "Sila pilih jenis kes anda"},
    bookingnumber: {main: "Nombor tempahan", err: "Sila isikan Nombor Tempahan anda untuk pengesahan bayaran balik"},
    flightnumber: {main: "Nombor penerbangan", err: ["Sila pilih Kod Penerbangan", "Sila isikan Nombor Penerbangan"]},
    flightdatetime: {main: "Tarikh dan masa penerbangan", err: ""},
    attachment: {main: "Lampiran", err: ""},
    feedback: {main: "Maklum balas", err: "Sila isikan Maklum Balas", extra: "Sila nyatakan jika anda ingin untuk meminta bayaran balik sepenuhnya (semua sektor) atau sektor yang terjejas sahaja"},
    paymentmethod: {main: "Pembayaran tempahan", err: "", extra: "Bayaran ini akan dipulangkan ke akaun kad kredit asal yang digunakan semasa tempahan, jadi ruangan berikut boleh diabaikan"},
    bankname: {main: "Nama bank", err: "Sila isikan Nama bank"},
    bankholdername: {main: "Nama Pemegang Akaun Bank", err: "Sila isikan Nama Pemegang Akaun Bank dalam abjad (a-z) sahaja"},
    bankaccountnumber: {main: "Nombor Akaun Bank", err: "Sila isikan Nombor Akaun Bank"},
    bankbranch: {main: "Cawangan Bank", err: "Sila isikan Cawangan Bank"},
    bankcurrency: {main: "Mata Wang Bank", err: "Sila masukkan nilai mata wang bank"},
    bankroutecode: {main: "Kod Perbankan Antarabangsa", err: "Sila isikan Kod Penghalaan"},
    bankroutenumber: {main: "Nombor Perbankan Antarabangsa", err: "Sila isikan Nombor Kod Penghalaan"},
    button: {reset: "Padam", submit: "Hantar"}
  },
  "id-id":{
    name: {main: "Nama depan dan nama belakang", err: ["Tulis Nama Depan","Tulis Nama Belakang"]},
    email: {main: "Alamat Email", err: "Tulis Alamat email"},
    mobilenum: {main: "Nomor telepon selular", err: "Nomor ponsel harus menyertakan kode panggilan internasional hanya dengan angka 0 sampai 9. ('spasi', '-', '+' dan karakter non-desimal lainnya tidak diperbolehkan)"},
    homenum: {main: "Nomor telepon rumah", err: ""},
    casecategory: {main: "Kategori Kasus", err: ""},
    typecategory: {main: "Jenis", err: "Silahkan pilih tipe kasus anda"},
    bookingnumber: {main: "Nomor Pembelian", err: "Masukkan Nomor Booking untuk verifikasi refund"},
    flightnumber: {main: "Nomor Penerbangan", err: ["Pilih Kode Maskapai","Masukkan Nomor Penerbangan"]},
    flightdatetime: {main: "Tanggal dan waktu penerbangan", err: ""},
    attachment: {main: "Lampiran", err: ""},
    feedback: {main: "Saran & Masukan", err: "Tulis Masukan", extra: "Mohon informasikan kepada kami untuk sektor penerbangan yang hendak dibatalkan dan diproses refund (semua sektor atau hanya sektor yang terkena dampak perubahan/pembatalan)"},
    paymentmethod: {main: "Pembayaran Pembelian", err: "", extra: "Pengembalian uang akan dikirimkan ke rekening kartu kredit yang Anda gunakan saat melakukan pemesanan, untuk itu kolom berikut dapat dikosongkan"},
    bankname: {main: "Nama Bank Anda", err: "Isilah nama Bank Anda"},
    bankholdername: {main: "Nama Pemegang Rekening Bank Anda", err: "Mohon untuk hanya mengisi abjad (a-z) untuk Nama Pemegang Rekening Bank"},
    bankaccountnumber: {main: "Nomor Rekening Bank Anda", err: "Isilah Nomor Rekening Bank Anda"},
    bankbranch: {main: "Nama Cabang Bank Anda", err: "Isilah Nama Cabang Bank Anda"},
    bankcurrency: {main: "Mata Uang Bank", err: "Harap isi dalam Mata Uang Bank"},
    bankroutecode: {main: "Kode Bank Internasional", err: "Isilah Kode Routing"},
    bankroutenumber: {main: "Nomor Bank Internasional", err: "Isilah Nomor Kode Routing"},
    button: {reset: "Kosongkan", submit: "Masukkan"}
  },
  "zh-cn":{
    name: {main: "英文名和姓", err: ["请填写名","请填写姓"]},
    email: {main: "电子邮件地址", err: "请填写电子邮箱地址"},
    mobilenum: {main: "手机号码", err: "移动电话号码必须包含国家号码，并且只能含有 0-9 的数字。（不允许包含空格、 0-、 0+，以及其他非十进制数字。）"},
    homenum: {main: "住家电话号码", err: ""},
    casecategory: {main: "个案类别", err: ""},
    typecategory: {main: "类型", err: "请选择案件类型"},
    bookingnumber: {main: "订购编号", err: "请输入您的预订编号进行退款验证"},
    flightnumber: {main: "航班编号", err: ["请选择航空公司代码", "请填写航班号"]},
    flightdatetime: {main: "航班日期和时间", err: ""},
    attachment: {main: "附件", err: ""},
    feedback: {main: "回馈", err: "请填写反馈", extra: "请指出您的退款要求:- 1、 全额退款 2、 只受影响航班"},
    paymentmethod: {main: "预订付款", err: "", extra: "退款将返还到您在预订时使用的信用卡帐户，因此一下栏目可以不填"},
    bankname: {main: "银行名称", err: "请填上银行名称"},
    bankholdername: {main: "银行帐户开户人姓名", err: "请以罗马字母(a-z)填写银行账户持有人姓名"},
    bankaccountnumber: {main: "银行账号", err: "请填上银行账号"},
    bankbranch: {main: "支行", err: "请填上银行分行"},
    bankcurrency: {main: "银行货币", err: "请填入银行币种"},
    bankroutecode: {main: "银行国际汇款路径", err: "请填上路径代码"},
    bankroutenumber: {main: "开户银行国际汇款代码", err: "请填上路径代码号码"},
    button: {reset: "清除", submit: "呈交"}
  },
  "zh-hk":{
    name: {main: "名字和姓氏", err: ["請填寫名字", "請填寫姓氏"]},
    email: {main: "電郵地址", err: "請填寫電郵地址"},
    mobilenum: {main: "手機電話", err: "流動電話需包括國際致電碼，其中僅可為0至9的數字。(不可輸入'空格'、 '-'、'+'和其他符號)"},
    homenum: {main: "家居電話", err: ""},
    casecategory: {main: "個案類別", err: ""},
    typecategory: {main: "種類", err: "請選擇案件類型"},
    bookingnumber: {main: "訂購編號", err: "請為退款認證程序填寫你的訂票編號"},
    flightnumber: {main: "航班編號", err: ["請選擇航空公司代號", "請填寫航班號碼"]},
    flightdatetime: {main: "航班日期和時間", err: ""},
    attachment: {main: "附件", err: ""},
    feedback: {main: "回饋", err: "請填寫意見", extra: "請指出您的退款要求:- 1、 全額退款 2、 只受影響航班"},
    paymentmethod: {main: "訂位付款", err: "", extra: "這款項將退回至最初訂位時所使用的信用卡賬戶內，因此以下的空格可以不需填寫"},
    bankname: {main: "銀行名稱", err: "請輸入銀行名稱"},
    bankholdername: {main: "銀行帳戶持有人姓名", err: "請在銀行賬戶持有人欄輸入英文字母 （a-z）"},
    bankaccountnumber: {main: "銀行帳戶號碼", err: "請輸入銀行戶口號碼"},
    bankbranch: {main: "銀行分行", err: "請輸入銀行分行"},
    bankcurrency: {main: "銀行貨幣", err: "請輸入銀行貨幣"},
    bankroutecode: {main: "銀行國際匯款路徑", err: "請輸入匯款路線(Routing Code)"},
    bankroutenumber: {main: "開戶銀行國際匯款代碼", err: "請輸入匯款路線號碼(Routing Code Number)"},
    button: {reset: "清除", submit: "提交"}
  },
  "th-th":{
    name: {main: "ชื่อและนามสกุล", err: ["กรุณากรอกชื่อ","กรุณากรอกนามสกุล"]},
    email: {main: "อีเมลแอดเดรส", err: "กรุณากรอกอีเมลแอดเดรส"},
    mobilenum: {main: "เบอร์โทรศัพท์มือถือ", err: "เบอร์โทรศัพท์มือถือจะต้องมีรหัสโทรระหว่างประเทศเป็นตัวเลข 0 ถึง 9 เท่านั้น (ไม่อนุญาตให้ใช้ 'เคาะว่าง', '-', '+' หรืออักขระอื่นที่ไม่ใช่ตัวเลข)"},
    homenum: {main: "เบอร์โทรศัพท์บ้าน", err: ""},
    casecategory: {main: "หมวดหมู่", err: ""},
    typecategory: {main: "ประเภท", err: "โปรดเลือกรายละเอียดหัวข้อ"},
    bookingnumber: {main: "หมายเลขจอง", err: "กรุณากรอกหมายเลขรายการจองของคุณเพื่อยืนยันการคืนเงิน"},
    flightnumber: {main: "หมายเลขเที่ยวบิน", err: ["กรุณาเลือกรหัสเที่ยวบิน", "กรุณากรอกเลขเที่ยวบิน"]},
    flightdatetime: {main: "วันที่และเวลาเดินทาง", err: ""},
    attachment: {main: "ไฟล์แนบ", err: ""},
    feedback: {main: "ความเห็น", err: "กรุณากรอกความเห็น", extra: "กรุณาระบุ ขอคืนเงินทั้งหมด (ทุกเที่ยวบินในหมายเลขการสำรองที่นั่ง) หรือ ระบุเฉพาะเที่ยวบินที่ได้รับผลกระทบ"},
    paymentmethod: {main: "ชำระเงินผ่าน", err: "", extra: "การคืนเงินนี้เป็นการคืนเงินสำหรับบัญชีบัตรเครดิตแรกที่ใช้ระหว่างทำรายการจอง สามารถละเว้นฟิลด์ต่อไปนี้ได้"},
    bankname: {main: "ชื่อธนาคาร", err: "โปรดกรอกชื่อธนาคาร"},
    bankholdername: {main: "ชื่อเจ้าของบัญชีธนาคาร", err: "กรุณากรอกชื่อเจ้าของบัญชีธนาคารด้วยอักษรภาษาอังกฤษเท่านั้น"},
    bankaccountnumber: {main: "หมายเลขบัญชีธนาคาร", err: "โปรดกรอกหมายเลขบัญชีธนาคาร"},
    bankbranch: {main: "สาขา", err: "โปรดกรอกสาขาธนาคาร"},
    bankcurrency: {main: "สกุลเงิน", err: "กรุณาระบุสกุลเงิน"},
    bankroutecode: {main: "International Bank Code", err: "โปรดกรอกรหัสการโอน"},
    bankroutenumber: {main: "International Bank Number", err: "โปรดกรอกหมายเลขรหัสการโอน"},
    button: {reset: "เคลียร์ข้อมูล", submit: "ส่ง"}
  },
}

const PAYMENY_METHODS: Object = {
  "en-gb": [ {value:"1", display:"Credit Card"}, {value:"3", display:"Cash"}, {value:"2", display:"Bank/Direct Debit"}, {value:"5", display:"Wellnet"} ],
  "ko-kr": [ {value:"1", display:"신용카드"}, {value:"3", display:"현금"}, {value:"2", display:"은행/자동이체"}, {value:"5", display:"Wellnet"} ],
  "ja-jp": [ {value:"1", display:"クレジットカード"}, {value:"3", display:"現金"}, {value:"2", display:"銀行／口座引き落とし"}, {value:"5", display:"Wellnet"} ],
  "ms-my": [ {value:"1", display:"Kad Kredit"}, {value:"3", display:"Tunai"}, {value:"2", display:"Bank/Debit Terus"}, {value:"5", display:"Wellnet"} ],
  "id-id": [ {value:"1", display:"Kartu Kredit"}, {value:"3", display:"Tunai"}, {value:"2", display:"Bank/Internet Banking"}, {value:"5", display:"Wellnet"} ],
  "zh-cn": [ {value:"1", display:"信用卡"}, {value:"3", display:"现金"}, {value:"2", display:"银行转帐/直接转帐"}, {value:"5", display:"Wellnet"} ],
  "zh-hk": [ {value:"1", display:"信用卡"}, {value:"3", display:"現金"}, {value:"2", display:"銀行轉帳/以借記卡直接付款"}, {value:"5", display:"Wellnet"} ],
  "th-th": [ {value:"1", display:"บัตรเครดิต"}, {value:"3", display:"เงินสด"}, {value:"2", display:"ธนาคาร/ตัดผ่านบัญชี"}, {value:"5", display:"Wellnet"} ]
}

const ACKNOWLEDGEMENT_MESSAGE: Object = {
  "en-gb": {message: "*All refunds are subjected to AirAsia's approval. Please ensure that the bank details provided belongs to the passenger or the contact person who initially made the booking.", check: "I hereby agree that the details provided above are correct and the refund can be processed to the account number listed"},
  "ko-kr": {message: "*모든 환불은 에어 아시아의 승인을 조건으로 진행 됩니다. 제공된 은행 계좌 정보는 승객 또는 최초 예약자의 것인지 확인해주시기 바랍니다", check: "본인은 모든 상세정보를 위와 같이 올바르게 제공하였으며, 환불은 명시 되어있는 계좌번호로 진행되는것에 동의합니다"},
  "ja-jp": {message: "*エアアジアにて承認済の返金対象便に限ります。お送りいただく銀行口座などの情報はご搭乗者様本人、またはご予約者様のものに限ります", check: "上に記した情報に間違いありません。 クレジットカードへの返金処理の場合を除き、払い戻しはこちらの銀行口座に対して行なわれます"},
  "ms-my": {message: "*Semua bayaran balik adalah tertakluk kepada kelulusan AirAsia. Sila pastikan bahawa butir butir bank yang diberikan adalah milik penumpang atau pihak yang membuat tempahan", check: "Saya dengan ini bersetuju bahawa butir-butir yang diberikan di atas adalah betul dan bayaran balik boleh diproses kepada nombor akaun yang disenaraikan"},
  "id-id": {message: "*Semua pengembalian biaya/dana akan berdasarkan persetujuan AirAsia. Mohon dipastikan bahwa informasi rekening bank yang diberikan adalah milik tamu yang bersangkutan atau tamu yang melakukan pembayaran atas pemesanan penerbangan", check: "Saya setuju bahwa rincian yang diberikan di atas adalah benar dan pengembalian dana dapat diproses ke nomor rekening yang tercantum"},
  "zh-cn": {message: "*所有退款都是由亚航授权下进行的。请确保该项银行信息是由原作出预订的客户所提供的", check: "本人同意以上所提供的银行信息是正确的而该项退款可以退还至本人所提供的帐户号码"},
  "zh-hk": {message: "*所有退款都是由亞航授權下進行的。請確保該項銀行信息是由原作出預訂的客戶所提供的", check: "本人同意以上所提供的銀行信息是正確的而該項退款可以退還至本人所提供的帳戶號碼"},
  "th-th": {message: "*การคืนเงินขึ้นอยู่กับดุลพินิจของสายการบินแอร์เอเชีย โปรดตรวจสอบหมายเลขบัญชีธนาคารต้องเป็นของผู้โดยสารที่มีชื่ออยู่ในหมายเลขการสำรองที่นั่ง หรือผู้ที่ดำเนินการสำรองที่นั่งเท่านั้น", check: "ข้าพเจ้ายอมรับว่าข้อมูลที่ให้ไว้ถูกต้อง และยินยอมให้สายการบินแอร์เอเชียดำเนินการคืนเงินเข้าหมายเลขบัญชีธนาคารที่ได้ระบุไว้"}
}

@Injectable()
export class FormService {
  getLabels(language:string){
    return LABELS[language];
  }
  getCaseOptions(language:string){
    return CASE_OPTIONS[language];
  }
  getTypeOptions(language:string, option:string){
    return TYPE_OPTIONS[language][option];
  }
  getDialCodes(){
    return COUNTRY_DIAL_CODE;
  }
  getFlightOptions(){
    return FLIGHT_CODE_OPTIONS;
  }
  getPaymentMethods(language:string){
    return PAYMENY_METHODS[language];
  }
  getAcknowledgementMessage(language:string){
    return ACKNOWLEDGEMENT_MESSAGE[language];
  }
}
